name: Platform

on: [push]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir.outputs.dir }}
            **/node_modules
            ~/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --pure-lockfile

  build-deploy-e2e:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check branch code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir.outputs.dir }}
            **/node_modules
            ~/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Gatsby Cache Folder
        uses: actions/cache@v2
        id: gatsby-public-folder
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-public-gatsby-${{ github.ref }}
          restore-keys: |
            ${{ runner.OS }}-public-gatsby-

      - name: Build
        run: yarn build --log-pages
        env:
          # incremental builds
          # https://www.gatsbyjs.org/docs/page-build-optimizations-for-incremental-data-changes/
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          NODE_ENV: production
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_INDEX_NAME: ${{ secrets.GATSBY_ALGOLIA_INDEX_NAME }}
          STRAPI_API_URL: https://raulmelo-dev-server.herokuapp.com

      - name: Save public folder as artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public/**/*

      - name: Save .cache as artifact
        uses: actions/upload-artifact@v2
        with:
          name: .cache
          path: .cache/**/*

      # These 2 steps is only happening here and not in a another step
      # Because it seems there's no way to force update a cache.
      # It means that even if I setup the gatsby cache up here
      # for the next step it'll use the old version of it.
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        id: deploy
        with:
          publish-dir: './public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          production-branch: main
          deploy-message: 'Deploy from GitHub Actions'
        env:
          NODE_ENV: production
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Cypress run
        run: yarn cypress run
        env:
          CYPRESS_BASE_URL: ${{ steps.deploy.outputs.deploy-url }}

  lint-and-unit:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check branch code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir.outputs.dir }}
            **/node_modules
            ~/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run ESLint
        run: yarn lint

      - name: Run Test
        run: yarn jest --color
        env:
          CI: true
