name: Web

on:
  workflow_dispatch:
    paths:
      - 'projects/web/**'
      - '.github/workflows/web.yml'
  push:
    paths:
      - 'projects/web/**'
      - '.github/workflows/web.yml'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch code
        uses: actions/checkout@v2

      - name: Setup nodejs environment
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Defines yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir.outputs.dir }}
            node_modules
            */*/node_modules
            ~/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --pure-lockfile

  deploy-storybook:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch code
        uses: actions/checkout@v2

      - name: Setup nodejs environment
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Defines yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir.outputs.dir }}
            node_modules
            */*/node_modules
            ~/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build storybook
        run: yarn web:docs:build
        # fixes
        # ERR! Error: [BABEL] /home/runner/work/raulmelo.dev/raulmelo.dev/projects/web/.storybook/generated-refs.js: `babel-preset-gatsby` has been loaded, which consumes config generated by the Gatsby CLI. Set `NODE_ENV=test` to bypass, or run `gatsby build` first.
        env:
          NODE_ENV: test

      - name: Deploy Storybook docs to Netlify
        uses: nwtgck/actions-netlify@v1.1
        id: deploy
        with:
          publish-dir: 'projects/web/storybook-public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          production-branch: main
          deploy-message: 'Deploy from GitHub Actions - Storybook'
        env:
          NODE_ENV: production
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STORYBOOK_SITE_ID }}

  build-and-checks:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch code
        uses: actions/checkout@v2

      - name: Setup nodejs environment
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Defines yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir.outputs.dir }}
            node_modules
            */*/node_modules
            ~/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run lint
        run: yarn web:lint

      - name: Run unit tests
        run: yarn web:test --color
        env:
          CI: true

      - name: Build website
        run: yarn web:build --log-pages
        env:
          # incremental builds
          # https://www.gatsbyjs.org/docs/page-build-optimizations-for-incremental-data-changes/
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          NODE_ENV: production
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_INDEX_NAME: ${{ secrets.GATSBY_ALGOLIA_INDEX_NAME }}
          STRAPI_API_URL: https://raulmelo-dev-server.herokuapp.com

      # This is only useful for debug purposes.
      # it might be enabled when needed.

      # - name: Save public folder as artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: public
      #     path: projects/web/public/**/*

      # - name: Save .cache as artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: .cache
      #     path: projects/web/.cache/**/*

      # These 2 steps is only happening here and not in a another step
      # Because it seems there's no way to force update a cache.
      # It means that even if I setup the gatsby cache up here
      # for the next step it'll use the old version of it.
      - name: Deploy website to Netlify - URL Preview
        uses: nwtgck/actions-netlify@v1.1
        id: deploy-preview
        with:
          publish-dir: 'projects/web/public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # The goal here is never deploy to production
          # So I can first preview and test on top of it
          # and only if it pass, triggers another action
          production-branch: some-weird-name-take-will-never-exists
          deploy-message: 'Deploy from GitHub Actions - PREVIEW'
        env:
          NODE_ENV: production
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Run End-to-End tests
        run: yarn web:e2e
        env:
          CYPRESS_BASE_URL: ${{ steps.deploy-preview.outputs.deploy-url }}

      - name: Deploy website to Netlify - Production
        uses: nwtgck/actions-netlify@v1.1
        id: deploy
        if: github.ref == 'refs/heads/main'
        with:
          publish-dir: 'projects/web/public'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          production-branch: main
          production-deploy: true
          deploy-message: 'Deploy from GitHub Actions - PRODUCTION'
        env:
          NODE_ENV: production
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
